contact_links:
  - name: Ask a question
    url: https://github.com/nitinmogalapalli/stackify/discussions
    about: Ask questions and discuss with other community members
  - name: Feature request
    url: https://github.com/nitinmogalapalli/stackify/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
